# Generated by Django 4.2.7 on 2025-09-10 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=4, help_text='Seating capacity must be between 1 and 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
